# Ultima versao do docker-compose
version: '3.7'

# RabbitMQ
services:
  rabbitmq:
    image: rabbitmq:3.7.7-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
